spring:
  datasource:
    url: jdbc:mysql://localhost:3306/account_book
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: jinoo
    password: 1234

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
